### ISSUE TITLE
Specify cli bin path

### ISSUE THREAD

**Issue by creepinson** [dprint/dprint-vscode#10]
I am having issues with vscode + deno + dprint. It says it cannot find dprint in vscode notifications, but in my zsh terminal `dprint init` and `dprint` work fine :/

And yes, I do have dprint in my path in my .zshrc configuration file, and that's why my terminal works fine. It just doesn't work when using vscode.
a possible solution would be to have a configuration option for the dprint vscode plugin to set the binary path.

**Comment by creepinson** [comment]
This might be because dprint could be detecting my shell as bash, but the actual shell is zsh.

**Comment by dsherret** [comment]
Ah, that makes sense and thanks for opening this. Yeah, this should be added.

**Comment by dsherret** [comment]
Just published this one as 0.4.0.

This vscode setting is now available:

```json
{
  "dprint.path": "/path/to/executable/dprint"
}
```
