### ISSUE TITLE
🙏🏻 [feat/req] Allow specification of configuration file from VSCode config

### ISSUE THREAD

**Issue by rivy** [dprint/dprint-vscode#12]
It would be great to be able to specify a non-default configuration file to be used by the `dprint` formatter for a given workspace.

**Comment by dsherret** [comment]
This is something I don’t want to do because it encourages using dprint without the default configuration, which is not a great experience, and it complicates all the implementations of editor plugins.

It sounds like implementing  https://github.com/dprint/dprint/issues/351 should meet your needs?

**Comment by rivy** [comment]
> It sounds like implementing [dprint/dprint#351](https://github.com/dprint/dprint/issues/351) should meet your needs?

Yes, that would fix it for me. I just wasn't sure which of the two (if either) would be more palatable to you, or, if other devs might have a different naming scheme in mind.

**Comment by dsherret** [comment]
Sounds good! Closing in favour of that solution.
