### ISSUE TITLE
Only works in first Workspace

### ISSUE THREAD

**Issue by mrgrain** [dprint/dprint-vscode#14]
Given a VSCode Workspace
and a configuration like the below,

`dprint-vscode` fails to format on save any other package than the first one.

An error is briefly displayed in the status bar.
![image](https://user-images.githubusercontent.com/379814/119646836-86cc6700-be17-11eb-8599-2ecd0e4fc100.png)

Changing the order of folders in the workspace config (e.g. moving `packageC` to position one) will result in that we can now format on save `packageC` but not the other ones.

```
{
  "folders": [
    {
      "path": "packageA"
    },
    {
      "path": "packageB"
    },
    {
      "path": "packageC"
    }
  ],
  "settings": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "dprint.dprint"
  }
}
```

**Comment by mrgrain** [comment]
`> Format Document with...` doesn't work either.

**Comment by dsherret** [comment]
Thanks! Probably related to #6 as I know I didn't make it work correctly for the first shot. Will take a look soon.

**Comment by mrgrain** [comment]
Yeah I wasn't sure if it's the same thing.

Maybe related, most other VSCode formatters I've seen support detecting the binary in the current (workspace) folder in addition to a globally installed one. Sometimes the fallback binary is shipped with the plugin.

Otherwise the plugin (and formatter) work great! Good work 🎉

**Comment by dsherret** [comment]
I'll do a release for this tomorrow probably. Sorry for the delay!
