### ISSUE TITLE
don't show error message on syntax error

### ISSUE THREAD

**Issue by sachinraja** [dprint/dprint-vscode#24]
I find the message that appears on the bottom right slightly annoying:
![image](https://user-images.githubusercontent.com/58836760/145696621-4f96bf45-3ee8-478e-8ca1-7e987538220f.png)
I would rather dprint just not format when there is a syntax error. I think an option to toggle showing the error messages would be great.

**Comment by dsherret** [comment]
Sure, this would be good to add.

**Comment by dsherret** [comment]
The notification no longer occurs in 0.10. The error now only shows in the "dprint" output channel (View > Output > select "dprint" from the drop down).
