### ISSUE TITLE
Option (and default) to prefer project-local dprint executable when available

### ISSUE THREAD

**Issue by jasonkuhrt** [dprint/dprint-vscode#29]
`dprint` can now be installed as an npm dependency. I would love that VSCode will use the version locally installed with the current project when possible. One benefit is that a team can ensure the same version is being used.

**Comment by MichalLytek** [comment]
I found it's enough to set `"dprint.path": "./node_modules/dprint/dprint",` 😉

**Comment by aminya** [comment]
> I found it's enough to set "dprint.path": "./node_modules/dprint/dprint", 😉

It doesn't work on Windows #32

**Comment by dsherret** [comment]
@aminya on windows you will need to specify an "exe" extension: `./node_modules/dprint/dprint.exe`

**Comment by aminya** [comment]
> @aminya on windows you will need to specify an "exe" extension: `./node_modules/dprint/dprint.exe`

It doesn't work. See https://github.com/dprint/dprint-vscode/issues/32#issuecomment-1126810626
