### ISSUE TITLE
Config glob becomes forkbomb, creates infinite processes

### ISSUE THREAD

**Issue by stagas** [dprint/dprint-vscode#31]
There are cyclic symlinks in my setup and one of these lines(or all 3) are causing the extension to create infinite number of processes, the only escape being is to force shutdown the computer. So essentially, a forkbomb:

https://github.com/dprint/dprint-vscode/blob/3379068a018210e925d0d09a33bf47148e7f4b00/src/WorkspaceService.ts#L86

https://github.com/dprint/dprint-vscode/blob/3379068a018210e925d0d09a33bf47148e7f4b00/src/extension.ts#L40

https://github.com/dprint/dprint-vscode/blob/3379068a018210e925d0d09a33bf47148e7f4b00/src/logger.ts#L41

I've fixed it locally by removing all the `**` globs and let it just use the `dprint.json` at the top level of the workspace, I think this should be the default behavior unless someone needs to do something else? What do you think? So a configuration for the `configGlob` defaulting to just `{dprint,.dprint,.dprintrc}.json`. I didn't bisect it to see which one is the actual cause as the experience of having to turn off the computer every time isn't pleasant, but it's obvious to me that these are problematic and need to be configured.

**Comment by dsherret** [comment]
@stagas could you provide your setup? I'm having trouble reproducing this. Thanks and sorry this happens!
