### ISSUE TITLE
dprint isn't found in "${workspaceFolder}/node_modules/dprint/dprint"

### ISSUE THREAD

**Issue by aminya** [dprint/dprint-vscode#32]
I am installing dprint using npm, but the extension fails to find it by specifying `dprint.path` to be `"${workspaceFolder}/node_modules/dprint/dprint"` on Windows. It works if I specify the full path.

**Comment by dsherret** [comment]
Try: `"./node_modules/dprint/dprint"` or `"./node_modules/dprint/dprint.exe"` on Windows. It doesn't seem like there's a good way to resolve vscode variables in configuration at the moment.

**Comment by aminya** [comment]
It doesn't work. I also want to avoid adding .exe. This setting is stored in the workspace settings.json. Not everyone on the team uses Windows,
![image](https://user-images.githubusercontent.com/16418197/168447966-f26a4ad5-7070-41dd-9ebf-ac29d7a32573.png)

**Comment by dsherret** [comment]
Yeah, it was broken on Windows. I fixed that and implemented #29. That said, this is a setting that should be user based and so if the user has Windows they will need to specify a `.exe` path.
