### ISSUE TITLE
Dprint task fails via VSCode extension on some particular files

### ISSUE THREAD

**Issue by sledorze** [dprint/dprint-vscode#40]
Here's the extension Output

[VERBOSE] Checking can format: /Users/stephaneledorze/Documents/projects/rebaze/nx-incubator/libs/filiburg/src/contexts/application.ts
[VERBOSE] Creating instance of dprint-plugin-typescript
[VERBOSE] Created instance of dprint-plugin-typescript in 0ms
[ERROR] Read task failed: Error: Expected success bytes, but found: [99, 111, 109, 101]
[ERROR] Error formatting text. Error: dprint's process exited while the message was in progress.

If I try to format in the repo via `yarn dprint fmt` or if I try `yarn dprint check` they work perfectly

I've tried to reproduce using the initial default config file generated by `dprint init` and it behaves the same

I've failed to shrink the repro as it appears that the problem is not specifically link to a specific part of a file
I can share the file privately however

**Comment by sledorze** [comment]
(unscientific guess: it may be correlated to the file size..)

**Comment by dsherret** [comment]
Interesting. I'm glad I have that success bytes verification. Does it occur when you make the file smaller?

Yeah, if you could share the file privately that would be beneficial then I can take a look into it (https://dprint.dev/contact/). Thanks!

**Comment by sledorze** [comment]
Seems to disappear when the file shrinks indeed
I'll send you the file right now :)

**Comment by dsherret** [comment]
Thanks! I received it. I will take a look later (hopefully after work today).

**Comment by sledorze** [comment]
Thanks a lot! :)

**Comment by YannHulot** [comment]
Having the same issue currently on big files. Works on small files.

**Comment by YannHulot** [comment]
Anything I can do to help fix this issue?

**Comment by dsherret** [comment]
Sorry for my delay... I have been working on a big feature at work and didn't get around to this until just now. So I tried this out on Windows and Linux, but I wasn't able to reproduce it. Finally I just now tried it on Mac and I was able to reproduce so it seems this is Mac specific for some reason. Looking at the code, I think I see the problem. Will submit a PR soon.

**Comment by dsherret** [comment]
Thanks for reporting this! The bug was a silly mistake and should now be fixed. I did a publish just now so in about 30 minutes the extension should be live with the fix in 0.13.2

**Comment by sledorze** [comment]
@dsherret Awesome! thanks!
My life (and others) quality has significantly increased this morning!
