### ISSUE TITLE
0.13.2 fails to format

### ISSUE THREAD

**Issue by mikehdt** [dprint/dprint-vscode#42]
A few hours ago I noticed VSC/dprint had stopped formatting files, and if the VSC window was unfocused, it'd just show an infinite progress bar for dprint in the lower corner. I hadn't noticed that VSC had installed an extension update, until I went and investigated a little.

I've rolled the dprint plugin back to 0.13.1 for now and it works again. Might need to check the code committed for 0.13.2? Happy to help debug if I can. This is on a Mac running MacOS 12.5.

**Comment by Nathusan** [comment]
I've got the same issue!

**Comment by dsherret** [comment]
Hey, what version of dprint are you using? I tried to reproduce this on mac this morning, but couldn't, then tried formatting on an old version of dprint that uses the old editor service and yeah it doesn't format anymore. If you upgrade to a new version it should be fixed, but that said I'm going to look into fixing it now for the old one.

**Comment by dsherret** [comment]
Ok, just published 0.13.3 which fixes this. Should be available within 30 minutes.

Sorry about that! The dprint vscode plugin is the only part of dprint that doesn't have a lot of tests and I've been slowly working on adding some in #37.

**Comment by mikehdt** [comment]
Thanks, will give it a whirl.

I've got dprint 0.30.3 installed generally, but I suspect that the code I work with has its own version embedded within the project (I think I've seen 0.19.1 floating around) so... yeah. It's an interesting one 😅
