### ISSUE TITLE
rg/ripgrep when searching for config file causes excessive CPU usage on startup

### ISSUE THREAD

**Issue by curtislarson** [dprint/dprint-vscode#47]
I have a vscode workspace that includes several very large monorepos and noticed my CPU usage would be pegged to 100% for 30s-1m when loading my workspace after I installed this extension. Disabling this extension made the problem go away but I figured it wasn't actually `dprint` causing the problem since I know from experience it's very efficient

I took a quick recording showing me reloading the window and the subsequent CPU spike:

https://user-images.githubusercontent.com/2141050/199844076-e3874ed6-8000-47f8-a195-ecfa5a394343.mov

And here is the culprit command:

```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar.unpacked/@vscode/ripgrep/bin/rg --files --hidden --case-sensitive -g /*/**/{dprint,.dprint,.dprintrc}.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/Thumbs.db --no-ignore --follow --no-config --no-ignore-global
```

Which led me to the glob used to find the dprint config file

https://github.com/dprint/dprint-vscode/blob/902df4459c88f14cfed80e60f1495064376f9854/src/constants.ts#L1

And some particularly suspect usages

https://github.com/dprint/dprint-vscode/blob/902df4459c88f14cfed80e60f1495064376f9854/src/WorkspaceService.ts#L68-L87

---

The first thing that comes to mind is also ignoring `node_modules` but that n^2 search seems unnecessary or could be made better with some short circuit checks.

I'd be happy to implement a fix or at least some short circuit paths since all my workspace folders contain a `dprint.json` file. I just want to check first to see if there are any recommendations before I dive further into the codebase.

**Comment by curtislarson** [comment]
Also noticed that this is very likely a similar issue to what was mentioned in https://github.com/dprint/dprint-vscode/issues/31 although I don't believe it's an actual "forkbomb", just an inefficient usage of the vscode `findFiles` api.

**Comment by dsherret** [comment]
> I'd be happy to implement a fix or at least some short circuit paths since all my workspace folders contain a dprint.json file. I just want to check first to see if there are any recommendations before I dive further into the codebase.

That would be great if you could take a look because I haven't been able to reproduce this and I don't have much free time the next few weeks. I don't have any recommendations.

**Comment by curtislarson** [comment]
Yeah `vscode.workspace.findFiles` searches for every file in every workspace folder (not individual workspace, which is confusing imo) and it was being called for each individual workspace folder initialization. So having 10 workspace folders would mean each folder searches all 10 workspace folders individually. Additionally there was logger code that would trigger another full workspace search after each workspace was initialized rather than using a cached value. I have a wip branch at https://github.com/curtislarson/dprint-vscode/tree/feat/faster-startup that I'll cleanup a bit and hopefully submit a PR tomorrow
