### ISSUE TITLE
don't focus outputChannel on errors

### ISSUE THREAD

**Issue by ivanhofer** [dprint/dprint-vscode#57]
When having network issues or if working offline, it is impossible to use VS Code with the `dprint` extension installed. The extension tries to download plugins several times and each time it fails, it focuses the output panel. So if someone tries to code or type something into the terminal, the focus gets lost and you can't really use VS Code for about 2 minutes until the extension does not perform retries anymore.

I can see that opening the output panel in case of an error makes sense, but it should do that only the first time. Focusing it every second is really annoying.

**Comment by dsherret** [comment]
Thanks for the suggestion. Should be fixed now in 0.13.6 (it should focus max one time per session)

**Comment by ivanhofer** [comment]
Thanks for the speedy fix!
