### ISSUE TITLE
Bug: v0.15.1 stopped working

### ISSUE THREAD

**Issue by xseman** [dprint/dprint-vscode#70]
Thanks for the great formatter and plugin! 

I'm facing an issue with the latest version; it seems to stop autoformatting,
also I can't find `dprint` command in command prompt to format. I rolled back to
`v0.15.0`, which works fine. Any tips for debugging the problem so I can provide
more information? Thanks!

**Comment by dsherret** [comment]
I don't understand why 0.15.1 wouldn't work, but 0.15.0 would. What does your setup look like? Are you using dprint from npm? What is the output in the "dprint" selection in the "output" window in vscode?

> also I can't find dprint command in command prompt to format.

How did you install it? Is it a local npm package for the project or was it installed globally?

**Comment by xseman** [comment]
I'm using the following configuration:

```plain
Linux 6.5 Fedora Linux 38
VSCode v1.83.1

dprint v0.41.0 installed within the project's node_modules directory, along with the latest plugins:
- typescript-0.88.2.wasm
- json-0.18.0.wasm
- markdown-0.16.2.wasm
```

Interestingly, after switching back from version 0.15.0 to the latest one, the
integration started working again. I apologize for not capturing any output
during the issue. If I encounter any more problems, I'll provide better
debugging information.
