### ISSUE TITLE
dprint-ignore comments ignored by vscode plugin but honoured when running the dprint cli directly

### ISSUE THREAD

**Issue by brad-jones** [dprint/dprint-vscode#76]
I have the following block of code that I'd like to remain formatted as is.
Running `dprint fmt` via the command line respects the comment & leaves the array as is.

![image](https://github.com/dprint/dprint-vscode/assets/2754772/c32a7f01-3ec1-4cf6-8d3d-16ca6caef92a)

However when I format the file via VsCode I get this.

![image](https://github.com/dprint/dprint-vscode/assets/2754772/8353b7bc-e394-4c25-a2fc-12adcae90cd0)

My config below.

Running `v0.45.0` of the dprint CLI.
Running `v0.16.0` of the `dprint.dprint` plugin.

_dprint.json_

```json
{
  "incremental": true,
  "lineWidth": 80,
  "newLineKind": "lf",
  "useTabs": false,
  "json": {},
  "toml": {},
  "typescript": {
    "deno": true,
    "ignoreFileCommentText": "dprint-ignore-file",
    "ignoreNodeCommentText": "dprint-ignore",
    "module.sortImportDeclarations": "caseInsensitive",
    "module.sortExportDeclarations": "caseInsensitive",
    "importDeclaration.preferSingleLine": true,
    "exportDeclaration.preferSingleLine": true
  },
  "markdown": {
    "textWrap": "always"
  },
  "dockerfile": {},
  "prettier": {
    "associations": [
      "**/*.{yml,yaml}"
    ]
  },
  "exec": {
    "commands": [
      {
        "command": "./.pixi/env/bin/shfmt",
        "exts": [
          "sh"
        ]
      }
    ]
  },
  "includes": [
    "**/*.{json,md,dockerfile,yml,yaml,toml,sh,ts}"
  ],
  "excludes": [
    "**/.pixi",
    "pixi.lock"
  ],
  "plugins": [
    "https://plugins.dprint.dev/toml-0.5.4.wasm",
    "https://plugins.dprint.dev/json-0.19.1.wasm",
    "https://plugins.dprint.dev/markdown-0.16.3.wasm",
    "https://plugins.dprint.dev/dockerfile-0.3.0.wasm",
    "https://plugins.dprint.dev/typescript-0.88.7.wasm",
    "https://plugins.dprint.dev/exec-0.4.4.json@c207bf9b9a4ee1f0ecb75c594f774924baf62e8e53a2ce9d873816a408cecbf7",
    "https://plugins.dprint.dev/prettier-0.32.0.json@fa93f05ab38f00c6de138f7747372585c661f79dfb11d7f1209c069b56680820"
  ]
}
```

_.vscode/settings.json_

```json
{
  "deno.enable": true,
  "deno.cacheOnSave": true,
  "editor.defaultFormatter": "dprint.dprint",
  "editor.formatOnPaste": true,
  "editor.formatOnSave": true,
}
```

**Comment by dsherret** [comment]
I'm not able to reproduce, but your config looks good. I think maybe something else is formatting for some reason. Do you have any global code formatting settings?

Can you try enabling the `dprint.verbose` setting in your .vscode/settings.json file?

```json
{
  "dprint.verbose": true
}
```

Then go to View > Output and in the output window, select "dprint" on the drop down in the top right. Do you see messages like this?

![image](https://github.com/dprint/dprint-vscode/assets/1609021/b7271e8b-2db9-4116-b716-d4e1ca97bbb3)

Also, maybe try `View > Command Palette`, type "Format Document With" then select "Dprint Code Formatter". Does the issue still occur?

**Comment by brad-jones** [comment]
Ah thats odd.

![image](https://github.com/dprint/dprint-vscode/assets/2754772/e926c580-b3a1-4764-8615-f342a22d4542)

🤦‍♂️ Umm yeah sorry never mind me, found this in my user config.

```json
"[typescript]": {
    "editor.defaultFormatter": "denoland.vscode-deno"
},
```

I think I had assumed `"editor.defaultFormatter": "dprint.dprint"` in the workspace settings was enough to override that.
