### ISSUE TITLE
Error starting LSP server when folder without installed dprint is opened

### ISSUE THREAD

**Issue by Ilyat1337** [dprint/dprint-vscode#79]
Extension version: latest (0.16.0)

Steps to reproduce:
1. Enable LSP: `"dprint.experimentalLsp": true`
2. Open any folder where dprint is not installed (f.e. empty folder)
3. Error occurs:
```
[Error - 3:13:06 PM] dprint client: couldn't create connection to server.
Launching server using command dprint failed. Error: spawn dprint ENOENT
[ERROR] Error initializing: Launching server using command dprint failed. Error: spawn dprint ENOENT
[WARN] Extension failed to start.
```

I think that dprint should be activated only in projects where it is configured (where `dprint.json` or\and dprint executable exists). All other projects should be ignored.

**Comment by dsherret** [comment]
Thank you for trying it out and reporting the bug!
