### ISSUE TITLE
dprint not working in vscode v1.90?

### ISSUE THREAD

**Issue by sweetim** [dprint/dprint-vscode#87]
it seems the latest VSCode broke the dprint plugin?
dprint formatting no longer works and recognized by VScode

```
Version: 1.90.0 (user setup)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631
```

below is the warning shown at the vscode settings json file

![image](https://github.com/dprint/dprint-vscode/assets/6851767/cf1b3fd2-2756-4727-87b9-a444ab7c9bfc)

**Comment by dsherret** [comment]
Works for me in 1.90.0

![image](https://github.com/dprint/dprint-vscode/assets/1609021/fab03c39-6383-438d-95ac-bf66dbc471e2)

Is the extension still enabled under extensions?

**Comment by sweetim** [comment]
yes, it is still there, 
i uninstall vscode and reinstall everything, it seems to work afterwards
