### ISSUE TITLE
Change json schema to allow trailing commas in dprint.jsonc

### ISSUE THREAD

**Issue by davidbludlow** [dprint/dprint-vscode#94]
In a dprint.jsonc file in vscode there will be yellow squiggly underlines/warnings if there are trailing commas:
![image](https://github.com/user-attachments/assets/91b68126-e827-494b-a119-db10d3651560)
It is improper to warn about the trailing commas. Dprint will insist on putting the trailing commas there itself when running with default settings, and rightly so, in my opinion.

This is easily fixable. I created a workaround by adding this to my .vscode/settings.json file
```json
  "json.schemas": [
    {
      "fileMatch": ["dprint.jsonc"],
      "schema": {
        "$ref": "dprint://schemas/config.json",
        "allowTrailingCommas": true,
      },
    },
  ],
```
That solves the problem, getting rid of the yellow squigglies and warnings, but there is no reason why `"allowTrailingCommas": true` can't be in the json schema by default. Let's add it to the json schema (which is partially defined in this vscode plugin and partially defined... elsewhere).

Note: I got the idea of augmenting the json schema with `"allowTrailingCommas": true` from https://github.com/microsoft/vscode/issues/102061#issuecomment-657080963 so it looks like this is an approved strategy.

**Comment by dsherret** [comment]
Should be fixed now. I'll do a release later. Thanks!
